// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

package eventing

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strconv"
	"strings"
	"time"

	indexerConstants "github.com/linuxfoundation/lfx-v2-indexer-service/pkg/constants"
	"github.com/linuxfoundation/lfx-v2-meeting-service/internal/domain"
	"github.com/linuxfoundation/lfx-v2-meeting-service/internal/domain/models"
	"github.com/linuxfoundation/lfx-v2-meeting-service/internal/logging"
	itx "github.com/linuxfoundation/lfx-v2-meeting-service/pkg/models/itx"
	"github.com/linuxfoundation/lfx-v2-meeting-service/pkg/utils"
	"github.com/nats-io/nats.go/jetstream"
)

// =============================================================================
// Meeting Event Handler
// =============================================================================

// MeetingDBRaw represents raw meeting data from v1 DynamoDB/NATS KV bucket
type MeetingDBRaw struct {
	// MeetingID is the meeting ID (can be a UUID or numeric ID)
	MeetingID string `json:"meeting_id"`

	// ProjID is the ID of the LF project
	ProjID string `json:"proj_id"`

	// Committee is the ID of the committee
	// It is a Global Secondary Index on the meeting table.
	Committee string `json:"committee"`

	// CommitteeFilters is the list of filters associated with the committee
	CommitteeFilters []string `json:"committee_filters"`

	// Committees is the list of committees associated with this meeting
	Committees []models.Committee `json:"committees,omitempty"`

	// User is the ID of the Zoom user that is set to host the meeting (who the meeting is scheduled for)
	// It is a Global Secondary Index on the meeting table.
	User string `json:"user_id"`

	// Topic is the topic of the meeting - this field exists in Zoom for a meeting
	Topic string `json:"topic"`

	// Agenda is the agenda of the meeting - this field exists in Zoom for a meeting
	Agenda string `json:"agenda"`

	// Visibility is the visibility of the meeting on the LFX platform
	Visibility string `json:"visibility"`

	// MeetingType is the type of meeting - this field exists in Zoom for a meeting
	MeetingType string `json:"meeting_type"`

	// StartTime is the start time of the meeting in RFC3339 format.
	// If the meeting is a recurring meeting, this is the start time of the first occurrence.
	StartTime string `json:"start_time"`

	// Timezone is the timezone of the meeting.
	// The value should be from the IANA Timezone Database (e.g. "America/Los_Angeles").
	Timezone string `json:"timezone"`

	// Duration is the duration of the meeting in minutes.
	Duration int `json:"duration"`

	// EarlyJoinTimeMinutes is the time in minutes before the meeting start time that the user can join the meeting.
	// This is needed because these meetings are scheduled on shared Zoom users and thus the meeting scheduler
	// needs to account for this early join time buffer.
	EarlyJoinTime int `json:"early_join_time"`

	// LastEndTime is the end time of the last occurrence of the meeting in unix timestamp format.
	// If the meeting is a non-recurring meeting, this is the end time of the one-time meeting.
	LastEndTime int64 `json:"last_end_time"`

	// HostKey is the host key of the Zoom user hosting the meeting.
	// It is a six-digit PIN that is rotated weekly by our change-host-keys cron job.
	// This host key is needed to be able to claim host during a meeting.
	HostKey string `json:"host_key"`

	// JoinUrl is the URL to the meeting join page maintained by the PCC team.
	// The URL is specific to the meeting ID and the password.
	// (e.g. https://zoom-lfx.dev.platform.linuxfoundation.org/meeting/93699735000?password=111)
	JoinURL string `json:"join_url"`

	// Password is a UUID that is generated by us when a meeting is created in this service.
	// It is used for the meeting join page to make it hard to find the URL without knowing the password.
	Password string `json:"password"`

	// Restricted is a flag that indicates if the meeting is restricted to only invited users of a meeting.
	// If restricted is false, then the meeting can be joined by anyone with the meeting ID and password.
	Restricted bool `json:"restricted"`

	// RecordingEnabled is a flag that indicates if the meeting is recorded.
	// If set to true, recording is enabled in Zoom since the recording is managed by Zoom.
	RecordingEnabled bool `json:"recording_enabled"`

	// TranscriptEnabled is a flag that indicates if the meeting transcript is enabled.
	// If set to true, recording is enabled in Zoom since the transcript is managed by Zoom.
	TranscriptEnabled bool `json:"transcript_enabled"`

	// RecordingAccess is the access level of the meeting recording within the LFX platform.
	RecordingAccess string `json:"recording_access"`

	// TranscriptAccess is the access level of the meeting transcript within the LFX platform.
	TranscriptAccess string `json:"transcript_access"`

	// CreatedAt is the timestamp of when the meeting was created in RFC3339 format.
	CreatedAt string `json:"created_at"`

	// ModifiedAt is the timestamp of when the meeting was last updated in RFC3339 format.
	ModifiedAt string `json:"modified_at"`

	// CreatedBy is the user that created the meeting.
	CreatedBy models.CreatedBy `json:"created_by"`

	// UpdatedBy is the user that last updated the meeting.
	UpdatedBy models.UpdatedBy `json:"updated_by"`

	// UpdatedByList is a list of users that have updated the meeting.
	UpdatedByList []models.UpdatedBy `json:"updated_by_list,omitempty"`

	// UseNewInviteEmailAddress is a flag that indicates if the meeting should use the new invite email address.
	// In January 2024, we switched to using a new email address as the organizer for meeting invites.
	// We needed to keep the old email address for existing meetings to avoid calendar issues.
	UseNewInviteEmailAddress bool `json:"use_new_invite_email_address"`

	// Recurrence is the recurrence pattern of the meeting.
	// This is managed by this service and not by Zoom. In Zoom, all meetings are scheduled as recurring with
	// no fixed time (type 3).
	Recurrence *RecurrenceDBRaw `json:"recurrence,omitempty"`

	// Occurrences is a list of [ZoomMeetingOccurrence] objects that represent the occurrences of the meeting.
	Occurrences []models.ZoomMeetingOccurrence `json:"occurrences,omitempty"`

	// CancelledOccurrences is a list of IDs of occurrences that have been cancelled.
	CancelledOccurrences []string `json:"cancelled_occurrences,omitempty"`

	// UpdatedOccurrences is a list of [UpdatedOccurrence] objects that represent the occurrences that have been updated
	// to a new set of values. Every occurrence has details that can be specific to that occurrence or those that follow,
	// such as the start time, duration, title, and description.
	UpdatedOccurrences []models.UpdatedOccurrence `json:"updated_occurrences,omitempty"`

	// IcsUIDTimezone is a field that is used to store the timezone of a meeting that is used to
	// generate the calendar UID. This was needed because if a meeting's timezone changed, the calendar UID
	// would change if we didn't anchor the UID to the timezone.
	IcsUIDTimezone string `json:"ics_uid_timezone,omitempty"`

	// IcsAdditionalUids is a list of additional calendar event UIDs that are used in the invites sent to registrants
	// for the meeting. All meetings have one UID that is the meeting ID to represent the initial recurrence pattern,
	// but for each updated occurrence that affects all of the following occurrences, another calendar event UID is needed
	// to represent that sequence of occurrences in ICS. Those UIDs are stored in the database to keep track of them.
	IcsAdditionalUids []string `json:"ics_additional_uids,omitempty"`

	// Passcode is the Zoom meeting passcode (flat v1 field, used to build ZoomConfig).
	Passcode string `json:"passcode,omitempty"`

	// ZoomAIEnabled indicates whether Zoom AI Companion is enabled (flat v1 field, used to build ZoomConfig).
	ZoomAIEnabled *bool `json:"zoom_ai_enabled,omitempty"`

	// RequireAISummaryApproval indicates whether AI summary approval is required (flat v1 field, used to build ZoomConfig).
	RequireAISummaryApproval *bool `json:"ai_summary_require_approval,omitempty"`

	// AISummaryAccess is the access level of the meeting AI summary within the LFX platform.
	// This is only relevant if [ZoomAIEnabled] is true.
	AISummaryAccess string `json:"ai_summary_access,omitempty"`

	// YoutubeUploadEnabled is a flag that indicates if the meeting's recording should be uploaded to Youtube
	YoutubeUploadEnabled bool `json:"youtube_upload_enabled,omitempty"`

	// ConcurrentZoomUserEnabled is a flag that indicates if the meeting is hosted on a zoom user with concurrent zoom licenses
	// enabled (which means it is hosted on a different set of pooled users).
	// TODO: remove the above ConcurrentZoomUserEnabled flag once all meetings have been moved to start using concurrent zoom licenses
	ConcurrentZoomUserEnabled bool `json:"concurrent_zoom_user_enabled,omitempty"`

	// LastBulkRegistrantJobStatus is the status of the last bulk insert job that was run to insert registrants
	LastBulkRegistrantJobStatus string `json:"last_bulk_registrant_job_status"`

	// LastBulkRegistrantsJobFailedCount is the total number of failed records in the last bulk insert job that was run to insert registrants
	LastBulkRegistrantsJobFailedCount int `json:"last_bulk_registrants_job_failed_count"`

	// LastBulkRegistrantsJobWarningCount is the total number of passed records with warnings in the last bulk insert job that was run to insert registrants
	LastBulkRegistrantsJobWarningCount int `json:"last_bulk_registrants_job_warning_count"`

	// LastMailingListMembersSyncJobStatus is the status of the last bulk insert job that was run to insert registrants
	LastMailingListMembersSyncJobStatus string `json:"last_mailing_list_members_sync_job_status"`

	// LastMailingListMembersSyncJobFailedCount is the total number of failed records in the last bulk insert job that was run to insert registrants
	LastMailingListMembersSyncJobFailedCount int `json:"last_mailing_list_members_sync_job_failed_count"`

	// MailingListGroupIDs is a list of group IDs that the meeting is associated with
	MailingListGroupIDs []string `json:"mailing_list_group_ids"`

	// LastMailingListMembersSyncJobWarningCount is the total number of passed records with warnings in the last bulk insert job that was run to insert registrants
	LastMailingListMembersSyncJobWarningCount int `json:"last_mailing_list_members_sync_job_warning_count"`

	// UseUniqueICSUID is a flag that indicates if the meeting should use a unique event ID for the calendar event.
	// Apply manually (generate uuid and store in this field) when a meeting has calendar issues, and we wish to use a separate unique uuid instead of the meeting ID.
	UseUniqueICSUID string `json:"use_unique_ics_uid"` // this is a uuid

	// ShowMeetingAttendees determines whether or not LFX One should show data about
	// meeting attendees to each other
	ShowMeetingAttendees bool `json:"show_meeting_attendees"`

	// Organizers is the list of usernames that are organizers of the meeting.
	Organizers []string `json:"organizers,omitempty"`
}

// GetArtifactVisibility returns the artifact visibility of the meeting.
func (m *MeetingDBRaw) GetArtifactVisibility() string {
	if m.RecordingAccess != "" {
		return m.RecordingAccess
	}
	if m.TranscriptAccess != "" {
		return m.TranscriptAccess
	}
	if m.AISummaryAccess != "" {
		return m.AISummaryAccess
	}
	return "meeting_hosts"
}

// UnmarshalJSON implements custom unmarshaling to handle both string and int inputs for numeric fields.
func (m *MeetingDBRaw) UnmarshalJSON(data []byte) error {
	type Alias MeetingDBRaw
	tmp := struct {
		Duration                                  interface{}       `json:"duration"`
		EarlyJoinTime                             interface{}       `json:"early_join_time"`
		LastEndTime                               interface{}       `json:"last_end_time"`
		LastBulkRegistrantsJobFailedCount         interface{}       `json:"last_bulk_registrants_job_failed_count"`
		LastBulkRegistrantsJobWarningCount        interface{}       `json:"last_bulk_registrants_job_warning_count"`
		LastMailingListMembersSyncJobFailedCount  interface{}       `json:"last_mailing_list_members_sync_job_failed_count"`
		LastMailingListMembersSyncJobWarningCount interface{}       `json:"last_mailing_list_members_sync_job_warning_count"`
		Occurrences                               []json.RawMessage `json:"occurrences"`
		UpdatedOccurrences                        []json.RawMessage `json:"updated_occurrences"`
		*Alias
	}{
		Alias: (*Alias)(m),
	}

	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}

	// Handle Duration
	switch v := tmp.Duration.(type) {
	case string:
		if v != "" {
			val, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			m.Duration = val
		}
	case float64:
		m.Duration = int(v)
	case int:
		m.Duration = v
	default:
		if v != nil {
			return fmt.Errorf("invalid type for duration: %T", v)
		}
	}

	// Handle EarlyJoinTime
	switch v := tmp.EarlyJoinTime.(type) {
	case string:
		if v != "" {
			val, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			m.EarlyJoinTime = val
		}
	case float64:
		m.EarlyJoinTime = int(v)
	case int:
		m.EarlyJoinTime = v
	default:
		if v != nil {
			return fmt.Errorf("invalid type for early_join_time_minutes: %T", v)
		}
	}

	// Handle LastEndTime (int64)
	switch v := tmp.LastEndTime.(type) {
	case string:
		if v != "" {
			val, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return err
			}
			m.LastEndTime = val
		}
	case float64:
		m.LastEndTime = int64(v)
	case int64:
		m.LastEndTime = v
	case int:
		m.LastEndTime = int64(v)
	default:
		if v != nil {
			return fmt.Errorf("invalid type for last_end_time: %T", v)
		}
	}

	// Handle LastBulkRegistrantsJobFailedCount
	switch v := tmp.LastBulkRegistrantsJobFailedCount.(type) {
	case string:
		if v != "" {
			val, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			m.LastBulkRegistrantsJobFailedCount = val
		}
	case float64:
		m.LastBulkRegistrantsJobFailedCount = int(v)
	case int:
		m.LastBulkRegistrantsJobFailedCount = v
	default:
		if v != nil {
			return fmt.Errorf("invalid type for last_bulk_registrants_job_failed_count: %T", v)
		}
	}

	// Handle LastBulkRegistrantsJobWarningCount
	switch v := tmp.LastBulkRegistrantsJobWarningCount.(type) {
	case string:
		if v != "" {
			val, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			m.LastBulkRegistrantsJobWarningCount = val
		}
	case float64:
		m.LastBulkRegistrantsJobWarningCount = int(v)
	case int:
		m.LastBulkRegistrantsJobWarningCount = v
	default:
		if v != nil {
			return fmt.Errorf("invalid type for last_bulk_registrants_job_warning_count: %T", v)
		}
	}

	// Handle LastMailingListMembersSyncJobFailedCount
	switch v := tmp.LastMailingListMembersSyncJobFailedCount.(type) {
	case string:
		if v != "" {
			val, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			m.LastMailingListMembersSyncJobFailedCount = val
		}
	case float64:
		m.LastMailingListMembersSyncJobFailedCount = int(v)
	case int:
		m.LastMailingListMembersSyncJobFailedCount = v
	default:
		if v != nil {
			return fmt.Errorf("invalid type for last_mailing_list_members_sync_job_failed_count: %T", v)
		}
	}

	// Handle LastMailingListMembersSyncJobWarningCount
	switch v := tmp.LastMailingListMembersSyncJobWarningCount.(type) {
	case string:
		if v != "" {
			val, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			m.LastMailingListMembersSyncJobWarningCount = val
		}
	case float64:
		m.LastMailingListMembersSyncJobWarningCount = int(v)
	case int:
		m.LastMailingListMembersSyncJobWarningCount = v
	default:
		if v != nil {
			return fmt.Errorf("invalid type for last_mailing_list_members_sync_job_warning_count: %T", v)
		}
	}

	// Occurrences are recomputed from RRULE calculation; discard the raw field (already shadowed above).
	m.Occurrences = nil

	// Decode UpdatedOccurrences manually to coerce Duration from string or number.
	if len(tmp.UpdatedOccurrences) > 0 {
		m.UpdatedOccurrences = make([]models.UpdatedOccurrence, 0, len(tmp.UpdatedOccurrences))
		for _, raw := range tmp.UpdatedOccurrences {
			var occTmp struct {
				OldOccurrenceID string                        `json:"old_occurrence_id"`
				NewOccurrenceID string                        `json:"new_occurrence_id"`
				Timezone        string                        `json:"timezone"`
				Duration        interface{}                   `json:"duration"`
				Title           string                        `json:"title"`
				Description     string                        `json:"description"`
				Recurrence      *models.ZoomMeetingRecurrence `json:"recurrence"`
				AllFollowing    bool                          `json:"all_following"`
			}
			if err := json.Unmarshal(raw, &occTmp); err != nil {
				return fmt.Errorf("failed to unmarshal updated_occurrence: %w", err)
			}
			occ := models.UpdatedOccurrence{
				OldOccurrenceID: occTmp.OldOccurrenceID,
				NewOccurrenceID: occTmp.NewOccurrenceID,
				Timezone:        occTmp.Timezone,
				Title:           occTmp.Title,
				Description:     occTmp.Description,
				Recurrence:      occTmp.Recurrence,
				AllFollowing:    occTmp.AllFollowing,
			}
			switch v := occTmp.Duration.(type) {
			case string:
				if v != "" {
					val, err := strconv.Atoi(v)
					if err != nil {
						return fmt.Errorf("invalid duration in updated_occurrence: %w", err)
					}
					occ.Duration = val
				}
			case float64:
				occ.Duration = int(v)
			case int:
				occ.Duration = v
			}
			m.UpdatedOccurrences = append(m.UpdatedOccurrences, occ)
		}
	}

	return nil
}

// RecurrenceDBRaw represents raw recurrence data from v1 DynamoDB
type RecurrenceDBRaw struct {
	Type           int    `json:"type"`
	RepeatInterval int    `json:"repeat_interval"`
	WeeklyDays     string `json:"weekly_days"`
	MonthlyDay     int    `json:"monthly_day"`
	MonthlyWeek    int    `json:"monthly_week"`
	MonthlyWeekDay int    `json:"monthly_week_day"`
	EndTimes       int    `json:"end_times"`
	EndDateTime    string `json:"end_date_time"`
}

// UnmarshalJSON implements custom unmarshaling to handle both string and int inputs for numeric fields.
func (r *RecurrenceDBRaw) UnmarshalJSON(data []byte) error {
	type Alias RecurrenceDBRaw
	tmp := struct {
		Type           interface{} `json:"type"`
		RepeatInterval interface{} `json:"repeat_interval"`
		WeeklyDays     interface{} `json:"weekly_days"`
		MonthlyDay     interface{} `json:"monthly_day"`
		MonthlyWeek    interface{} `json:"monthly_week"`
		MonthlyWeekDay interface{} `json:"monthly_week_day"`
		EndTimes       interface{} `json:"end_times"`
		EndDateTime    interface{} `json:"end_date_time"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}

	// Handle Type (string from Meltano, int/float64 from other sources)
	switch v := tmp.Type.(type) {
	case string:
		if v != "" {
			val, err := strconv.Atoi(v)
			if err != nil {
				return fmt.Errorf("invalid type format: %w", err)
			}
			r.Type = val
		}
	case float64:
		r.Type = int(v)
	case int:
		r.Type = v
	default:
		if v != nil {
			return fmt.Errorf("invalid type for type: %T", v)
		}
	}

	// Handle RepeatInterval
	switch v := tmp.RepeatInterval.(type) {
	case string:
		if v != "" {
			val, err := strconv.Atoi(v)
			if err != nil {
				return fmt.Errorf("invalid repeat_interval format: %w", err)
			}
			r.RepeatInterval = val
		}
	case float64:
		r.RepeatInterval = int(v)
	case int:
		r.RepeatInterval = v
	default:
		if v != nil {
			return fmt.Errorf("invalid type for repeat_interval: %T", v)
		}
	}

	// Handle MonthlyDay
	switch v := tmp.MonthlyDay.(type) {
	case string:
		if v != "" {
			val, err := strconv.Atoi(v)
			if err != nil {
				return fmt.Errorf("invalid monthly_day format: %w", err)
			}
			r.MonthlyDay = val
		}
	case float64:
		r.MonthlyDay = int(v)
	case int:
		r.MonthlyDay = v
	default:
		if v != nil {
			return fmt.Errorf("invalid type for monthly_day: %T", v)
		}
	}

	// Handle MonthlyWeek
	switch v := tmp.MonthlyWeek.(type) {
	case string:
		if v != "" {
			val, err := strconv.Atoi(v)
			if err != nil {
				return fmt.Errorf("invalid monthly_week format: %w", err)
			}
			r.MonthlyWeek = val
		}
	case float64:
		r.MonthlyWeek = int(v)
	case int:
		r.MonthlyWeek = v
	default:
		if v != nil {
			return fmt.Errorf("invalid type for monthly_week: %T", v)
		}
	}

	// Handle MonthlyWeekDay
	switch v := tmp.MonthlyWeekDay.(type) {
	case string:
		if v != "" {
			val, err := strconv.Atoi(v)
			if err != nil {
				return fmt.Errorf("invalid monthly_week_day format: %w", err)
			}
			r.MonthlyWeekDay = val
		}
	case float64:
		r.MonthlyWeekDay = int(v)
	case int:
		r.MonthlyWeekDay = v
	default:
		if v != nil {
			return fmt.Errorf("invalid type for monthly_week_day: %T", v)
		}
	}

	// Handle EndTimes
	switch v := tmp.EndTimes.(type) {
	case string:
		if v != "" {
			val, err := strconv.Atoi(v)
			if err != nil {
				return fmt.Errorf("invalid end_times format: %w", err)
			}
			r.EndTimes = val
		}
	case float64:
		r.EndTimes = int(v)
	case int:
		r.EndTimes = v
	default:
		if v != nil {
			return fmt.Errorf("invalid type for end_times: %T", v)
		}
	}

	// Handle WeeklyDays
	switch v := tmp.WeeklyDays.(type) {
	case string:
		r.WeeklyDays = v
	default:
		if v != nil {
			r.WeeklyDays = fmt.Sprintf("%v", v)
		}
	}

	// Handle EndDateTime
	switch v := tmp.EndDateTime.(type) {
	case string:
		r.EndDateTime = v
	default:
		if v != nil {
			r.EndDateTime = fmt.Sprintf("%v", v)
		}
	}

	return nil
}

// mapUpdatedOccurrences maps v1 field names to v2 field names in updated occurrences.
// V1 stores topic→title and agenda→description on each occurrence entry.
func mapUpdatedOccurrences(v1Data map[string]interface{}, occurrences []models.UpdatedOccurrence) []models.UpdatedOccurrence {
	rawOccs, ok := v1Data["updated_occurrences"].([]interface{})
	if !ok || len(rawOccs) != len(occurrences) {
		return occurrences
	}
	for i, rawOcc := range rawOccs {
		occMap, ok := rawOcc.(map[string]interface{})
		if !ok {
			continue
		}
		if topic, ok := occMap["topic"].(string); ok && topic != "" {
			occurrences[i].Title = topic
		}
		if agenda, ok := occMap["agenda"].(string); ok && agenda != "" {
			occurrences[i].Description = agenda
		}
	}
	return occurrences
}

// buildMeetingZoomConfig constructs a ZoomConfig from flat v1 fields on the raw meeting.
// V1 stores these as top-level fields rather than a nested zoom_config object.
func buildMeetingZoomConfig(m *MeetingDBRaw) *models.ZoomConfig {
	cfg := &models.ZoomConfig{
		MeetingID: m.MeetingID,
		Passcode:  m.Passcode,
	}
	if m.ZoomAIEnabled != nil {
		cfg.AICompanionEnabled = *m.ZoomAIEnabled
	}
	if m.RequireAISummaryApproval != nil {
		cfg.AISummaryRequireApproval = *m.RequireAISummaryApproval
	}
	return cfg
}

// convertMapToMeetingData converts v1 meeting data to v2 format
func convertMapToMeetingData(
	ctx context.Context,
	v1Data map[string]interface{},
	idMapper domain.IDMapper,
	mappingsKV jetstream.KeyValue,
	logger *slog.Logger,
) (*models.MeetingEventData, error) {
	// Convert map to JSON bytes, then to MeetingDBRaw
	jsonBytes, err := json.Marshal(v1Data)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal v1Data to JSON: %w", err)
	}

	var rawMeeting MeetingDBRaw
	if err := json.Unmarshal(jsonBytes, &rawMeeting); err != nil {
		return nil, fmt.Errorf("failed to unmarshal meeting data: %w", err)
	}

	meeting := &models.MeetingEventData{
		ID:                                       rawMeeting.MeetingID,
		ProjectSFID:                              rawMeeting.ProjID,
		Committee:                                rawMeeting.Committee,
		CommitteeFilters:                         rawMeeting.CommitteeFilters,
		User:                                     rawMeeting.User,
		Title:                                    rawMeeting.Topic,
		Description:                              rawMeeting.Agenda,
		StartTime:                                rawMeeting.StartTime,
		Duration:                                 rawMeeting.Duration,
		Timezone:                                 rawMeeting.Timezone,
		Visibility:                               rawMeeting.Visibility,
		Restricted:                               rawMeeting.Restricted,
		MeetingType:                              rawMeeting.MeetingType,
		EarlyJoinTimeMinutes:                     rawMeeting.EarlyJoinTime,
		LastEndTime:                              rawMeeting.LastEndTime,
		HostKey:                                  rawMeeting.HostKey,
		JoinURL:                                  rawMeeting.JoinURL,
		Password:                                 rawMeeting.Password,
		RecordingEnabled:                         rawMeeting.RecordingEnabled,
		TranscriptEnabled:                        rawMeeting.TranscriptEnabled,
		RecordingAccess:                          rawMeeting.RecordingAccess,
		TranscriptAccess:                         rawMeeting.TranscriptAccess,
		YoutubeUploadEnabled:                     rawMeeting.YoutubeUploadEnabled,
		ConcurrentZoomUserEnabled:                rawMeeting.ConcurrentZoomUserEnabled,
		UseNewInviteEmailAddress:                 rawMeeting.UseNewInviteEmailAddress,
		CancelledOccurrences:                     rawMeeting.CancelledOccurrences,
		UpdatedOccurrences:                       mapUpdatedOccurrences(v1Data, rawMeeting.UpdatedOccurrences),
		IcsUIDTimezone:                           rawMeeting.IcsUIDTimezone,
		IcsAdditionalUids:                        rawMeeting.IcsAdditionalUids,
		ZoomConfig:                               *buildMeetingZoomConfig(&rawMeeting),
		AISummaryAccess:                          rawMeeting.AISummaryAccess,
		LastBulkRegistrantJobStatus:              rawMeeting.LastBulkRegistrantJobStatus,
		LastBulkRegistrantsJobFailedCount:        rawMeeting.LastBulkRegistrantsJobFailedCount,
		LastBulkRegistrantsJobWarningCount:       rawMeeting.LastBulkRegistrantsJobWarningCount,
		LastMailingListMembersSyncJobStatus:      rawMeeting.LastMailingListMembersSyncJobStatus,
		LastMailingListMembersSyncJobFailedCount: rawMeeting.LastMailingListMembersSyncJobFailedCount,
		LastMailingListMembersSyncJobWarningCount: rawMeeting.LastMailingListMembersSyncJobWarningCount,
		MailingListGroupIDs:                       rawMeeting.MailingListGroupIDs,
		UseUniqueICSUID:                           rawMeeting.UseUniqueICSUID,
		ShowMeetingAttendees:                      rawMeeting.ShowMeetingAttendees,
		UpdatedByList:                             rawMeeting.UpdatedByList,
		CreatedAt:                                 rawMeeting.CreatedAt,
		UpdatedAt:                                 rawMeeting.ModifiedAt,
		CreatedBy:                                 rawMeeting.CreatedBy,
		UpdatedBy:                                 rawMeeting.UpdatedBy,
		Organizers:                                rawMeeting.Organizers,
	}
	if meeting.Organizers == nil {
		meeting.Organizers = []string{}
	}

	// Skip if created by this service (prevent sync loops)
	if shouldSkipSync(rawMeeting.UpdatedBy.UserID) {
		logger.InfoContext(ctx, "skipping sync - created by this service", "last_modified_by", rawMeeting.UpdatedBy.UserID)
		return nil, nil
	}

	// Validate required fields
	if rawMeeting.MeetingID == "" || rawMeeting.ProjID == "" {
		return nil, fmt.Errorf("missing required fields: meeting_id or proj_id")
	}

	// Map project ID from v1 SFID to v2 UID. A missing mapping is not an error —
	// the caller checks ProjectUID == "" and skips (no retry), matching v1-sync-helper behaviour.
	projectUID, err := idMapper.MapProjectV1ToV2(ctx, rawMeeting.ProjID)
	if err == nil {
		meeting.ProjectUID = projectUID
	}

	committees := getCommitteesForMeeting(ctx, rawMeeting.MeetingID, idMapper, mappingsKV, logger)
	meeting.Committees = committees

	// Map the primary committee v1 ID to v2 UID
	if rawMeeting.Committee != "" {
		committeeUID, err := idMapper.MapCommitteeV1ToV2(ctx, rawMeeting.Committee)
		if err != nil {
			logger.With(logging.ErrKey, err).WarnContext(ctx, "failed to map primary committee ID", "v1_id", rawMeeting.Committee)
		} else {
			meeting.CommitteeUID = committeeUID
		}
	}

	// Map recurrence from raw to model
	if rawMeeting.Recurrence != nil {
		r := rawMeeting.Recurrence
		meeting.Recurrence = &models.ZoomMeetingRecurrence{
			Type:           r.Type,
			RepeatInterval: r.RepeatInterval,
			WeeklyDays:     r.WeeklyDays,
			MonthlyDay:     r.MonthlyDay,
			MonthlyWeek:    r.MonthlyWeek,
			MonthlyWeekDay: r.MonthlyWeekDay,
			EndTimes:       r.EndTimes,
			EndDateTime:    r.EndDateTime,
		}
	}

	// Determine artifact visibility (priority: recording > transcript > ai_summary)
	meeting.ArtifactVisibility = rawMeeting.GetArtifactVisibility()

	// Dynamically derive ShowMeetingAttendees — only enabled for board meetings
	// belonging to a specific project, regardless of what is stored in the KV bucket.
	meeting.ShowMeetingAttendees = strings.EqualFold(rawMeeting.MeetingType, "board") &&
		rawMeeting.ProjID == "a0941000002wBz9AAE"

	// Calculate occurrences if recurring
	calc := NewOccurrenceCalculator(logger)

	// Calculate 100 future occurrences (not including past ones)
	occurrences, err := calc.CalculateOccurrences(
		ctx,
		*meeting,
		false, // pastOccurrences - don't include past
		false, // includeCancelled - don't include cancelled
		100,   // numOccurrencesToReturn
	)
	if err != nil {
		logger.With(logging.ErrKey, err).WarnContext(ctx, "failed to calculate occurrences")
	}
	meeting.Occurrences = make([]models.ZoomMeetingOccurrence, len(occurrences))
	for i, occurrence := range occurrences {
		meeting.Occurrences[i] = models.ZoomMeetingOccurrence{
			OccurrenceID: occurrence.OccurrenceID,
			StartTime:    occurrence.StartTime.Format(time.RFC3339),
			Duration:     occurrence.Duration,
			IsCancelled:  occurrence.IsCancelled,
			Title:        occurrence.Title,
			Description:  occurrence.Description,
			Recurrence:   occurrence.Recurrence,
			// TODO: do we need to determine the response counts before we index the data
			ResponseCountYes: 0,
			ResponseCountNo:  0,
			RegistrantCount:  0,
		}
	}

	return meeting, nil
}

// handleMeetingUpdate processes updates to meeting records
func (h *EventHandlers) handleMeetingUpdate(
	ctx context.Context,
	key string,
	v1Data map[string]interface{},
) (retry bool) {
	funcLogger := h.logger.With("key", key, "handler", "meeting")
	funcLogger.DebugContext(ctx, "processing meeting update")

	// Check if this is a soft delete
	if isDeleted, ok := v1Data["_sdc_deleted_at"].(string); ok && isDeleted != "" {
		return h.handleMeetingDelete(ctx, key, v1Data)
	}

	// Convert v1Data to meeting event data
	meetingData, err := convertMapToMeetingData(ctx, v1Data, h.idMapper, h.v1MappingsKV, funcLogger)
	if err != nil {
		funcLogger.With(logging.ErrKey, err).ErrorContext(ctx, "failed to convert v1Data to meeting")
		return isTransientError(err)
	}
	if meetingData == nil {
		return false // Intentionally skipped (e.g., loop prevention)
	}

	// Validate required fields
	if meetingData.ID == "" {
		funcLogger.ErrorContext(ctx, "missing required fields in meeting data")
		return false
	}
	if meetingData.ProjectUID == "" {
		funcLogger.InfoContext(ctx, "skipping meeting sync - parent project not found in mappings", "project_sfid", meetingData.ProjectSFID)
		return false
	}
	funcLogger = funcLogger.With("meeting_id", meetingData.ID)

	// Determine action (created vs updated)
	mappingKey := fmt.Sprintf("v1_meetings.%s", meetingData.ID)
	indexerAction := indexerConstants.ActionCreated
	if _, err := h.v1MappingsKV.Get(ctx, mappingKey); err == nil {
		indexerAction = indexerConstants.ActionUpdated
	}

	// Publish to indexer and FGA-sync
	if err := h.publisher.PublishMeetingEvent(ctx, string(indexerAction), meetingData); err != nil {
		funcLogger.With(logging.ErrKey, err).ErrorContext(ctx, "failed to publish meeting event")
		return isTransientError(err)
	}

	// Store mapping
	if _, err := h.v1MappingsKV.Put(ctx, mappingKey, []byte("1")); err != nil {
		funcLogger.With(logging.ErrKey, err).WarnContext(ctx, "failed to store meeting mapping")
	}

	funcLogger.InfoContext(ctx, "successfully processed meeting")
	return false
}

// handleMeetingDelete processes meeting deletions
func (h *EventHandlers) handleMeetingDelete(ctx context.Context, key string, _ map[string]interface{}) (retry bool) {
	meetingID := extractIDFromKey(key, "itx-zoom-meetings-v2.")
	mappingKey := fmt.Sprintf("v1_meetings.%s", meetingID)
	if h.isTombstoned(ctx, mappingKey) {
		h.logger.DebugContext(ctx, "meeting delete already processed, skipping", "meeting_id", meetingID)
		return false
	}
	return h.handleMeetingTypeDelete(ctx, key, meetingID, []byte(meetingID), meetingDeleteConfig{
		indexerSubject:         "lfx.index.v1_meeting",
		deleteAllAccessSubject: "lfx.delete_all_access.v1_meeting",
		tombstoneKeyFmts:       []string{"v1_meetings.%s"},
	})
}

// =============================================================================
// Meeting Mapping Event Handler
// =============================================================================

// handleMeetingMappingUpdate processes updates to meeting-committee mappings
func (h *EventHandlers) handleMeetingMappingUpdate(
	ctx context.Context,
	key string,
	v1Data map[string]interface{},
) (retry bool) {
	funcLogger := h.logger.With("key", key, "handler", "meeting_mapping")
	funcLogger.InfoContext(ctx, "processing meeting mapping update")

	// Check if this is a soft delete
	if isDeleted, ok := v1Data["_sdc_deleted_at"].(string); ok && isDeleted != "" {
		return h.handleMeetingMappingDelete(ctx, key, v1Data)
	}

	// Extract meeting ID and mapping data
	meetingID := utils.GetString(v1Data["meeting_id"])
	mappingID := utils.GetString(v1Data["id"])
	committeeID := utils.GetString(v1Data["committee_id"])

	if meetingID == "" || mappingID == "" {
		funcLogger.WarnContext(ctx, "missing required fields in mapping")
		return false
	}

	// Update committee mappings in KV bucket
	if err := updateCommitteeMappings(ctx, meetingID, mappingID, committeeID, v1Data, h.v1MappingsKV, funcLogger); err != nil {
		funcLogger.With(logging.ErrKey, err).ErrorContext(ctx, "failed to update committee mappings")
		return isTransientError(err)
	}

	// Re-trigger meeting indexing
	shouldRetry := h.retriggerMeetingIndexing(ctx, meetingID)
	if shouldRetry {
		return true
	}

	funcLogger.InfoContext(ctx, "successfully processed meeting mapping update")
	return false
}

// handleMeetingMappingDelete processes meeting-committee mapping deletions
func (h *EventHandlers) handleMeetingMappingDelete(
	ctx context.Context,
	key string,
	v1Data map[string]interface{},
) (retry bool) {
	if v1Data == nil {
		h.logger.WarnContext(ctx, "no v1Data available for meeting mapping delete, skipping", "key", key)
		return false
	}

	meetingID := utils.GetString(v1Data["meeting_id"])
	mappingID := extractIDFromKey(key, "itx-zoom-meetings-mappings-v2.")

	if meetingID == "" || mappingID == "" {
		h.logger.WarnContext(ctx, "missing required fields in mapping deletion")
		return false
	}

	funcLogger := h.logger.With("meeting_id", meetingID, "mapping_id", mappingID, "handler", "meeting_mapping_delete")
	funcLogger.InfoContext(ctx, "processing meeting mapping deletion")

	if err := removeCommitteeMapping(ctx, meetingID, mappingID, h.v1MappingsKV, funcLogger); err != nil {
		if isTransientError(err) {
			return true
		}
		funcLogger.With(logging.ErrKey, err).ErrorContext(ctx, "failed to remove committee mapping")
		return false
	}

	shouldRetry := h.retriggerMeetingIndexing(ctx, meetingID)
	if shouldRetry {
		return true
	}

	funcLogger.InfoContext(ctx, "successfully processed meeting mapping deletion")
	return false
}

// =============================================================================
// Helper Functions
// =============================================================================

// Conversion and utility functions

func getCommitteesForMeeting(
	ctx context.Context,
	meetingID string,
	idMapper domain.IDMapper,
	mappingsKV jetstream.KeyValue,
	logger *slog.Logger,
) []models.Committee {
	key := fmt.Sprintf("meeting-mappings.%s", meetingID)
	entry, err := mappingsKV.Get(ctx, key)
	if err != nil {
		return nil
	}

	var mappings map[string]map[string]interface{}
	if err := json.Unmarshal(entry.Value(), &mappings); err != nil {
		logger.With(logging.ErrKey, err).WarnContext(ctx, "failed to unmarshal committee mappings")
		return nil
	}

	committees := make([]models.Committee, 0, len(mappings))
	for _, mapping := range mappings {
		committeeID := utils.GetStringFromMap(mapping, "committee_id")
		if committeeID != "" {
			committeeUID, err := idMapper.MapCommitteeV1ToV2(ctx, committeeID)
			if err != nil {
				logger.With(logging.ErrKey, err).WarnContext(ctx, "failed to map committee ID", "v1_id", committeeID)
				continue
			}

			filters := utils.GetStringSliceFromMap(mapping, "committee_filters")
			committees = append(committees, models.Committee{
				UID:                   committeeUID,
				AllowedVotingStatuses: utils.CastSlice[itx.CommitteeFilter](filters),
			})
		}
	}

	return committees
}

func updateCommitteeMappings(
	ctx context.Context,
	meetingID string,
	mappingID string,
	committeeID string,
	v1Data map[string]interface{},
	mappingsKV jetstream.KeyValue,
	logger *slog.Logger,
) error {
	mappingsKey := fmt.Sprintf("meeting-mappings.%s", meetingID)
	var mappings map[string]map[string]interface{}

	entry, err := mappingsKV.Get(ctx, mappingsKey)
	if err != nil {
		mappings = make(map[string]map[string]interface{})
	} else {
		if err := json.Unmarshal(entry.Value(), &mappings); err != nil {
			logger.With(logging.ErrKey, err).ErrorContext(ctx, "failed to unmarshal existing mappings")
			return fmt.Errorf("failed to unmarshal existing mappings: %w", err)
		}
	}

	// Update or add mapping
	mappingData := map[string]interface{}{"committee_id": committeeID}
	if filters := utils.GetStringSliceFromMap(v1Data, "committee_filters"); len(filters) > 0 {
		mappingData["committee_filters"] = filters
	}
	mappings[mappingID] = mappingData

	// Store updated mappings
	mappingsJSON, err := json.Marshal(mappings)
	if err != nil {
		return fmt.Errorf("failed to marshal mappings: %w", err)
	}

	if _, err := mappingsKV.Put(ctx, mappingsKey, mappingsJSON); err != nil {
		return fmt.Errorf("failed to store mappings: %w", err)
	}

	return nil
}

func removeCommitteeMapping(
	ctx context.Context,
	meetingID string,
	mappingID string,
	mappingsKV jetstream.KeyValue,
	logger *slog.Logger,
) error {
	mappingsKey := fmt.Sprintf("meeting-mappings.%s", meetingID)
	entry, err := mappingsKV.Get(ctx, mappingsKey)
	if err != nil {
		return nil // No mappings found
	}

	var mappings map[string]map[string]interface{}
	if err := json.Unmarshal(entry.Value(), &mappings); err != nil {
		return fmt.Errorf("failed to unmarshal mappings: %w", err)
	}

	delete(mappings, mappingID)

	if len(mappings) == 0 {
		return mappingsKV.Delete(ctx, mappingsKey)
	}

	mappingsJSON, err := json.Marshal(mappings)
	if err != nil {
		return fmt.Errorf("failed to marshal updated mappings: %w", err)
	}

	_, err = mappingsKV.Put(ctx, mappingsKey, mappingsJSON)
	return err
}

func (h *EventHandlers) retriggerMeetingIndexing(
	ctx context.Context,
	meetingID string,
) (retry bool) {
	meetingKey := fmt.Sprintf("itx-zoom-meetings-v2.%s", meetingID)
	meetingEntry, err := h.v1ObjectsKV.Get(ctx, meetingKey)
	if err != nil {
		h.logger.With(logging.ErrKey, err).WarnContext(ctx, "meeting not found during retrigger")
		return false // Meeting might be deleted
	}

	meetingData, err := decodeData(meetingEntry.Value())
	if err != nil {
		h.logger.With(logging.ErrKey, err).ErrorContext(ctx, "failed to decode meeting data")
		return false
	}

	// Re-process the meeting
	return h.handleMeetingUpdate(ctx, meetingKey, meetingData)
}
