# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: v2
name: lfx-one-meeting-service
description: LFX one Meeting Service chart
type: application
version: 2.0.0
appVersion: "latest"

dependencies:
  - name: lfx-service
    version: 1.0.0
    repository: file://../../../lfx-v2-helm/charts/lfx-service
    # repository: oci://ghcr.io/linuxfoundation/lfx-service/chart