# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
name: Publish Container Branch

"on":
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    name: Publish Container
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920  # v2.20.0
        with:
          egress-policy: audit
          disable-sudo: true

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v5
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v5
        with:
          go-version-file: go.mod
      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445  # v0.10
        with:
          version: v0.18.0
      - name: Prepare container tag
        id: container_tag
        env:
          HEAD_REF: "${{ github.head_ref }}"
        run: |
          container_tag=$(echo "$HEAD_REF" | sed 's/[^_0-9a-zA-Z]/-/g' | cut -c -127)
          echo tag="$container_tag" >> "$GITHUB_OUTPUT"
      - name: Build meeting-api for PR
        env:
          VERSION: ${{ steps.container_tag.outputs.tag }}
        run: |
          BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')
          GIT_COMMIT="${{ github.sha }}"
          GIT_COMMIT="${GIT_COMMIT:0:7}"
          export BUILD_TIME
          export GIT_COMMIT
          ko build github.com/linuxfoundation/lfx-v2-meeting-service/cmd/meeting-api \
            -B \
            --platform linux/amd64,linux/arm64 \
            -t ${{ github.sha }} \
            -t ${{ steps.container_tag.outputs.tag }} \
            --sbom spdx
