---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: MegaLinter

"on":
  pull_request: null

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      # Git Checkout
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411  # v2.19.4
        with:
          egress-policy: audit
          disable-sudo: true

      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v4
        with:
          fetch-depth: 0

      # MegaLinter
      - name: MegaLinter
        id: ml
        # Use the Go flavor.
        uses: oxsecurity/megalinter/flavors/go@0e3ce9b9c8c10effb9b269509cc47ca17cae31c7  # v9.5.0
        env:
          # All available variables are described in documentation
          # https://megalinter.io/configuration/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Allow GITHUB_TOKEN for working around rate limits (aquasecurity/trivy#7668).
          REPOSITORY_TRIVY_UNSECURED_ENV_VARIABLES: GITHUB_TOKEN
          # Set the Go toolchain to auto so that megalinter uses the correct go version for the service.
          GOTOOLCHAIN: auto
